// Pure text/data helpers for turning dense lesson content (public/lessons/
// day-*.json, generated by scripts/extract_lessons.py from the source .docx
// series) into scannable bullets instead of a wall of text. Kept dependency-free
// (no React) so the exact same logic renders in LessonDetail.tsx and audits the
// whole corpus in src/data/lessonContentRules.test.ts — one implementation, so
// a fix here covers every existing lesson and any new one added later.
//
// Before adding new lesson content, see scripts/LESSON_CHECKLIST.md.

// Every lesson's opening callout is authored with a rhetorical lead-in line
// ("ทำไม neonatologist ต้องเข้าใจ <topic>?") before the actual key-points
// summary — redundant once it's inside the app, so it's stripped for display
// only (the source .docx on OneDrive is left untouched).
export const WHY_INTRO_RE = /^ทำไม\s*neonatologist\s*ต้องเข้าใจ[^\n]*\?\s*\n+/;

export function stripWhyIntro(text: string): string {
  return text.replace(WHY_INTRO_RE, '');
}

export interface NumberedList {
  intro: string;
  items: string[];
}

// Lots of blocks (callouts, self-check answers, the occasional dense bullet) are
// authored as one sentence enumerating "(1) ... (2) ... (3) ..." separated by
// semicolons or commas — readable in a Word doc, but a wall of text on a phone
// screen. When that pattern is present, split it into a lead-in plus one line
// per numbered point instead of rendering it as a single flowing paragraph.
export function splitNumberedList(body: string): NumberedList | null {
  if (body.includes('\n') || !/\(1\)/.test(body) || !/\(2\)/.test(body)) return null;
  const firstMarker = body.indexOf('(1)');
  if (firstMarker < 0) return null;
  const intro = body.slice(0, firstMarker).trim();
  // Most lists in this corpus use ";" or "," between points, but a good
  // number use a sentence-ending "." instead (e.g. "...เดียวกัน. (2) NIH
  // 2001..."), which used to fall through to splitDenseProse and stay
  // crammed into one paragraph because its sentence-boundary check requires
  // an uppercase/Thai letter right after the period — never the case when
  // "(" comes next.
  const items = body
    .slice(firstMarker)
    .split(/[;,.]\s*(?=\(\d+\)\s)/)
    .map((s) => s.replace(/^\(\d+\)\s*/, '').trim())
    .filter(Boolean);
  return items.length >= 2 ? { intro, items } : null;
}

// Most dense text has no explicit "(1)...(2)..." numbering at all — it's just
// several clauses/sentences run together. Fall back through progressively
// looser separators (semicolons, then sentence-ending periods, then em dashes)
// to still break it into scannable lines. Each guard below exists because it
// caught a real false-positive in the lesson corpus:
//  - a semicolon immediately followed by a digit is a citation ("Pediatrics
//    2010;126:585"), not a list separator, so it requires a following letter.
//  - a period immediately touching a digit on either side is a decimal/dose
//    ("0.5 mL"), not a sentence end.
//  - "et al." is the single biggest source of false sentence breaks (citations
//    like "Anand KJ et al. Lancet 2004") — explicitly excluded.
const SEMI_SPLIT_RE = /;\s+(?=[A-Za-zก-๙])/;
const SENTENCE_BOUNDARY_RE = /(?<!\d)\.(?!\d)\s+(?=[A-Zก-๙])/g;
const DASH_SPLIT_RE = /\s+—\s+/;

function splitOnSentences(body: string): string[] {
  const parts: string[] = [];
  let last = 0;
  let match: RegExpExecArray | null;
  const re = new RegExp(SENTENCE_BOUNDARY_RE.source, 'g');
  while ((match = re.exec(body))) {
    const idx = match.index;
    if (/\bet\s+al$/i.test(body.slice(Math.max(0, idx - 8), idx))) continue;
    parts.push(body.slice(last, idx + 1).trim());
    last = idx + match[0].length;
  }
  parts.push(body.slice(last).trim());
  return parts.filter(Boolean);
}

export function splitDenseProse(body: string): string[] | null {
  if (body.includes('\n') || body.length <= 150) return null;
  const bySemi = body
    .split(SEMI_SPLIT_RE)
    .map((s) => s.trim())
    .filter(Boolean);
  if (bySemi.length >= 2) return bySemi;
  const bySentence = splitOnSentences(body);
  if (bySentence.length >= 2) return bySentence;
  const byDash = body
    .split(DASH_SPLIT_RE)
    .map((s) => s.trim())
    .filter(Boolean);
  if (byDash.length >= 2) return byDash;
  return null;
}

export interface DuplicateCaptionTable {
  caption: string;
  dataRows: string[][];
}

// A few tables were extracted with a caption meant to span the whole table,
// but the same caption text ended up copied into every column of the first
// row instead of one wide cell — showing the same paragraph two/three/four
// times side by side. Detect that shape so it can be shown once instead.
export function extractDuplicateCaption(rows: string[][]): DuplicateCaptionTable | null {
  const firstRow = rows[0];
  if (firstRow.length > 1 && new Set(firstRow).size === 1 && firstRow[0].length > 40) {
    return { caption: firstRow[0], dataRows: rows.slice(1) };
  }
  return null;
}

export type SingleColumnTableShape =
  | { kind: 'pearlCards'; cards: { title: string; body: string }[] }
  | { kind: 'titleBody'; title: string; body: string };

// Single-column tables in this corpus are always one of two shapes: a run of
// self-contained "title\nbody" rows (e.g. "5 Bedside Pearls" cards) or a lone
// title + body pair authored as a 2-row table instead of a `callout` block.
// Both render identically to a callout box.
export function classifySingleColumnTable(cells: string[]): SingleColumnTableShape | null {
  if (cells.length >= 3 && cells.every((c) => c.includes('\n'))) {
    return {
      kind: 'pearlCards',
      cards: cells.map((c) => {
        const nl = c.indexOf('\n');
        return { title: c.slice(0, nl), body: c.slice(nl + 1) };
      }),
    };
  }
  if (cells.length === 2) {
    return { kind: 'titleBody', title: cells[0], body: cells[1] };
  }
  return null;
}
