// Full lesson reader. Content is fetched on demand from public/lessons/day-*.json
// (generated by scripts/extract_lessons.py) rather than bundled, keeping the
// initial app JS small even with 200+ lessons' worth of text.

import { useEffect, useState } from 'react';
import { warm, font } from '../../theme/tokens';
import { DisclaimerBanner } from '../../components/Disclaimer';
import { lessonForDay, lessonPath, LESSON_SOURCE_FOLDER_URL, bookLabel, lessonSourceHint } from '../../data/lessons';
import { isLessonDone, markLesson } from '../../lib/storage';

type Block =
  | { type: 'h1' | 'h2' | 'li' | 'p' | 'callout'; text: string }
  | { type: 'table'; rows: string[][] };

interface LessonContent {
  day: number;
  book: string;
  chapter: number;
  title: string;
  authors: string;
  blocks: Block[];
}

type LoadState =
  | { status: 'loading' }
  | { status: 'error' }
  | { status: 'ready'; content: LessonContent };

export function LessonDetail({ day, onBack }: { day: number; onBack?: () => void }) {
  const [state, setState] = useState<LoadState>({ status: 'loading' });
  const [done, setDone] = useState(() => isLessonDone(day));
  const meta = lessonForDay(day);

  useEffect(() => {
    let cancelled = false;
    setState({ status: 'loading' });
    fetch(lessonPath(day))
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<LessonContent>;
      })
      .then((content) => {
        if (!cancelled) setState({ status: 'ready', content });
      })
      .catch(() => {
        if (!cancelled) setState({ status: 'error' });
      });
    return () => {
      cancelled = true;
    };
  }, [day]);

  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        background: warm.paper,
        color: warm.ink,
        fontFamily: font.ui,
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px 18px 8px',
        }}
      >
        <button
          type="button"
          onClick={onBack}
          style={{ border: 'none', background: 'none', color: warm.terra, fontSize: 14, fontWeight: 600, cursor: 'pointer', padding: 0 }}
        >
          ‹ Lessons
        </button>
        <button
          type="button"
          onClick={() => {
            markLesson(day, !done);
            setDone(!done);
          }}
          style={{
            border: `1px solid ${done ? warm.sage : warm.line}`,
            background: done ? warm.sage : 'transparent',
            color: done ? '#fff' : warm.muted,
            fontSize: 11,
            fontWeight: 700,
            padding: '4px 10px',
            borderRadius: 999,
            cursor: 'pointer',
          }}
        >
          {done ? '✓ Done' : 'Mark done'}
        </button>
      </div>

      <div style={{ padding: '2px 22px 6px' }}>
        <div style={{ fontSize: 11, fontFamily: font.mono, color: warm.muted, marginBottom: 4 }}>
          Day {meta.day} · {bookLabel(meta.book)} Ch {meta.chapter}
        </div>
        <div style={{ fontFamily: font.head, fontSize: 22, lineHeight: 1.15, fontWeight: 800, letterSpacing: -0.4 }}>
          {meta.title}
        </div>
        <div style={{ fontSize: 12, color: warm.muted, marginTop: 4, fontStyle: 'italic' }}>{meta.authors}</div>
      </div>

      <div style={{ flex: 1, overflowY: 'auto', padding: '6px 18px 20px' }}>
        <DisclaimerBanner compact />

        {state.status === 'loading' && (
          <div style={{ color: warm.muted, fontSize: 13, padding: '20px 0', textAlign: 'center' }}>Loading lesson…</div>
        )}

        {state.status === 'error' && (
          <div style={{ color: warm.muted, fontSize: 13, padding: '20px 0', textAlign: 'center' }}>
            Couldn&apos;t load this lesson's content. Check your connection and try again.
          </div>
        )}

        {state.status === 'ready' && (
          <>
            <LessonBody blocks={state.content.blocks} />
            <a
              href={LESSON_SOURCE_FOLDER_URL}
              target="_blank"
              rel="noreferrer noopener"
              style={{
                display: 'block',
                textAlign: 'center',
                marginTop: 16,
                padding: '11px 14px',
                borderRadius: 10,
                background: warm.terra,
                color: '#fff',
                fontWeight: 700,
                fontSize: 13,
                textDecoration: 'none',
              }}
            >
              Open original lesson document →
            </a>
            <div style={{ fontSize: 10.5, color: warm.muted, marginTop: 8, lineHeight: 1.4, textAlign: 'center' }}>
              Opens the shared OneDrive folder — look for &quot;{lessonSourceHint(meta)}&quot;.
            </div>
          </>
        )}
      </div>
    </div>
  );
}

function LessonBody({ blocks }: { blocks: Block[] }) {
  return (
    <div>
      {blocks.map((b, i) => {
        switch (b.type) {
          case 'callout':
            return (
              <div
                key={i}
                style={{
                  background: '#FBEFE3',
                  border: `1px solid ${warm.ochre}55`,
                  borderRadius: 10,
                  padding: '10px 12px',
                  marginBottom: 12,
                  fontSize: 12.5,
                  color: warm.ink2,
                  lineHeight: 1.55,
                  whiteSpace: 'pre-wrap',
                }}
              >
                {b.text}
              </div>
            );
          case 'h1':
            return (
              <div
                key={i}
                style={{
                  fontFamily: font.head,
                  fontSize: 16,
                  fontWeight: 800,
                  color: warm.terra,
                  marginTop: i === 0 ? 0 : 20,
                  marginBottom: 8,
                }}
              >
                {b.text}
              </div>
            );
          case 'h2':
            return (
              <div
                key={i}
                style={{
                  fontSize: 13,
                  fontWeight: 700,
                  color: warm.ink,
                  marginTop: 12,
                  marginBottom: 6,
                }}
              >
                {b.text}
              </div>
            );
          case 'li':
            return (
              <div key={i} style={{ display: 'flex', gap: 8, marginBottom: 6 }}>
                <span aria-hidden style={{ color: warm.terra, fontSize: 12, lineHeight: 1.6 }}>
                  ·
                </span>
                <span style={{ flex: 1, fontSize: 12.5, color: warm.ink2, lineHeight: 1.55 }}>{b.text}</span>
              </div>
            );
          case 'table':
            return (
              <div key={i} style={{ overflowX: 'auto', marginBottom: 12 }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11.5 }}>
                  <tbody>
                    {b.rows.map((row, ri) => (
                      <tr key={ri} style={{ borderBottom: `1px solid ${warm.line}` }}>
                        {row.map((cell, ci) => (
                          <td
                            key={ci}
                            style={{
                              padding: '6px 8px',
                              verticalAlign: 'top',
                              fontWeight: ri === 0 ? 700 : 400,
                              color: ri === 0 ? warm.ink : warm.ink2,
                              background: ri === 0 ? warm.paperDeep : 'transparent',
                              whiteSpace: 'pre-wrap',
                            }}
                          >
                            {cell}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            );
          case 'p':
          default:
            return (
              <div key={i} style={{ fontSize: 12.5, color: warm.ink2, lineHeight: 1.6, marginBottom: 8, whiteSpace: 'pre-wrap' }}>
                {b.text}
              </div>
            );
        }
      })}
    </div>
  );
}
