// Full lesson reader. Content is fetched on demand from public/lessons/day-*.json
// (generated by scripts/extract_lessons.py) rather than bundled, keeping the
// initial app JS small even with 200+ lessons' worth of text.

import { useEffect, useState } from 'react';
import { warm, font, chipTone } from '../../theme/tokens';
import { DisclaimerBanner } from '../../components/Disclaimer';
import {
  lessonForDay,
  lessonPath,
  lessonImagePath,
  LESSON_SOURCE_FOLDER_URL,
  bookLabel,
  lessonSourceHint,
  lessonAttribution,
  hasSourceDoc,
} from '../../data/lessons';
import { useProgress } from '../../lib/useProgress';
import { setLessonDone } from '../../lib/progress';
import { useBookmarks } from '../../lib/useBookmarks';
import { recordActivity, getFontScale, setFontScale, type FontScale } from '../../lib/storage';
import { setBookmark } from '../../lib/bookmarks';
import { lessonBookmarkId } from '../../lib/bookmarkIds';
import {
  stripWhyIntro,
  splitNumberedList,
  splitDenseProse,
  splitArrowChain,
  extractDuplicateCaption,
  classifySingleColumnTable,
} from '../../lib/lessonFormatting';

type Block =
  | { type: 'h1' | 'h2' | 'li' | 'p' | 'callout'; text: string }
  | { type: 'table'; rows: string[][] }
  | { type: 'image'; src: string };

interface LessonContent {
  day: number;
  book: string;
  chapter: number;
  title: string;
  authors: string;
  blocks: Block[];
}

type LoadState =
  | { status: 'loading' }
  | { status: 'error' }
  | { status: 'ready'; content: LessonContent };

function NumberedItems({ items, accent, textColor }: { items: string[]; accent: string; textColor: string }) {
  return (
    <>
      {items.map((item, idx) => (
        <div key={idx} style={{ display: 'flex', gap: 6, marginBottom: idx === items.length - 1 ? 0 : 5 }}>
          <span aria-hidden style={{ color: accent, fontWeight: 700, lineHeight: 1.5, flexShrink: 0 }}>
            {idx + 1}.
          </span>
          <span style={{ flex: 1, whiteSpace: 'pre-wrap', color: textColor }}>{item}</span>
        </div>
      ))}
    </>
  );
}

function PlainBulletItems({ items, accent, textColor }: { items: string[]; accent: string; textColor: string }) {
  return (
    <>
      {items.map((item, idx) => (
        <div key={idx} style={{ display: 'flex', gap: 6, marginBottom: idx === items.length - 1 ? 0 : 5 }}>
          <span aria-hidden style={{ color: accent, lineHeight: 1.6, flexShrink: 0 }}>
            ·
          </span>
          <span style={{ flex: 1, whiteSpace: 'pre-wrap', color: textColor }}>{item}</span>
        </div>
      ))}
    </>
  );
}

// A causal chain ("A → B → C") reads as one continuous flow, not separate
// points — so the first step stands alone and every later step is prefixed
// with the arrow that led to it, instead of a bullet dot or a number.
function ArrowChainSteps({ steps, accent, textColor }: { steps: string[]; accent: string; textColor: string }) {
  return (
    <>
      <div style={{ marginBottom: 5, whiteSpace: 'pre-wrap', color: textColor }}>{steps[0]}</div>
      {steps.slice(1).map((step, idx) => (
        <div key={idx} style={{ display: 'flex', gap: 6, marginBottom: idx === steps.length - 2 ? 0 : 5 }}>
          <span aria-hidden style={{ color: accent, fontWeight: 700, lineHeight: 1.5, flexShrink: 0 }}>
            →
          </span>
          <span style={{ flex: 1, whiteSpace: 'pre-wrap', color: textColor }}>{step}</span>
        </div>
      ))}
    </>
  );
}

// Shared box for anything shaped like "title line + body paragraph": real
// `callout` blocks, but also `table` blocks that were authored the same way
// (a 2-row single-column table, or a run of "Pearl" cards) — see the `table`
// case below.
function CalloutBox({ title, body, scale }: { title: string | null; body: string; scale: number }) {
  const parsed = splitNumberedList(body);
  const prose = parsed ? null : splitDenseProse(body);
  const chain = parsed || prose ? null : splitArrowChain(body);
  return (
    <div
      style={{
        background: '#FBEFE3',
        border: `1px solid ${warm.ochre}55`,
        borderRadius: 10,
        padding: '10px 12px',
        marginBottom: 12,
        fontSize: 12.5 * scale,
        color: warm.ink2,
        lineHeight: 1.55,
      }}
    >
      {title && <div style={{ whiteSpace: 'pre-wrap', marginBottom: 4 }}>{title}</div>}
      {parsed ? (
        <>
          {parsed.intro && <div style={{ whiteSpace: 'pre-wrap', marginBottom: 6 }}>{parsed.intro}</div>}
          <NumberedItems items={parsed.items} accent={warm.ochre} textColor={warm.ink2} />
        </>
      ) : prose ? (
        <PlainBulletItems items={prose} accent={warm.ochre} textColor={warm.ink2} />
      ) : chain ? (
        <ArrowChainSteps steps={chain} accent={warm.ochre} textColor={warm.ink2} />
      ) : (
        <div style={{ whiteSpace: 'pre-wrap' }}>{body}</div>
      )}
    </div>
  );
}

export function LessonDetail({ day, onBack }: { day: number; onBack?: () => void }) {
  const [state, setState] = useState<LoadState>({ status: 'loading' });
  const [retryToken, setRetryToken] = useState(0);
  const progress = useProgress();
  const done = Boolean(progress[String(day)]);
  const meta = lessonForDay(day);
  const bookmarks = useBookmarks();
  const bookmarkId = lessonBookmarkId(day);
  const bookmarked = Boolean(bookmarks[bookmarkId]);
  const [fontScale, setFontScaleState] = useState<FontScale>(() => getFontScale());

  function cycleFontScale() {
    const next = (fontScale === 4 ? 1 : ((fontScale + 1) as FontScale));
    setFontScaleState(next);
    setFontScale(next);
  }

  useEffect(() => {
    let cancelled = false;
    setState({ status: 'loading' });
    fetch(lessonPath(day))
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<LessonContent>;
      })
      .then((content) => {
        if (!cancelled) {
          setState({ status: 'ready', content });
          recordActivity(); // reading a lesson keeps the streak alive, even if not marked done
        }
      })
      .catch(() => {
        if (!cancelled) setState({ status: 'error' });
      });
    return () => {
      cancelled = true;
    };
  }, [day, retryToken]);

  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        background: warm.paper,
        color: warm.ink,
        fontFamily: font.ui,
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px 18px 8px',
        }}
      >
        <button
          type="button"
          onClick={onBack}
          style={{ border: 'none', background: 'none', color: warm.terra, fontSize: 14, fontWeight: 600, cursor: 'pointer', padding: 0 }}
        >
          ‹ Lessons
        </button>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <button
            type="button"
            onClick={cycleFontScale}
            aria-label={`Text size ${fontScale}×. Tap to change.`}
            title="Change text size"
            style={{
              border: `1px solid ${fontScale > 1 ? warm.terra : warm.line}`,
              background: fontScale > 1 ? '#F4DDD0' : 'transparent',
              color: fontScale > 1 ? warm.terraDeep : warm.muted,
              fontSize: 11,
              fontWeight: 700,
              minWidth: 28,
              height: 28,
              borderRadius: 999,
              cursor: 'pointer',
              padding: '0 8px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 2,
            }}
          >
            <span aria-hidden style={{ fontSize: 13 }}>
              Aa
            </span>
            {fontScale > 1 && <span aria-hidden>{fontScale}×</span>}
          </button>
          <button
            type="button"
            onClick={() => setBookmark(bookmarkId, !bookmarked)}
            aria-pressed={bookmarked}
            aria-label={bookmarked ? 'Remove bookmark' : 'Bookmark this lesson'}
            style={{
              border: `1px solid ${bookmarked ? warm.ochre : warm.line}`,
              background: bookmarked ? '#FBEFE3' : 'transparent',
              color: bookmarked ? warm.ochre : warm.muted,
              fontSize: 14,
              width: 28,
              height: 28,
              borderRadius: '50%',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              padding: 0,
            }}
          >
            {bookmarked ? '★' : '☆'}
          </button>
          <button
            type="button"
            onClick={() => setLessonDone(day, !done)}
            style={{
              border: `1px solid ${done ? warm.sage : warm.line}`,
              background: done ? warm.sage : 'transparent',
              color: done ? '#fff' : warm.muted,
              fontSize: 11,
              fontWeight: 700,
              padding: '4px 10px',
              borderRadius: 999,
              cursor: 'pointer',
            }}
          >
            {done ? '✓ Done' : 'Mark done'}
          </button>
        </div>
      </div>

      <div style={{ padding: '2px 22px 6px' }}>
        <div style={{ fontSize: 11, fontFamily: font.mono, color: warm.muted, marginBottom: 4 }}>
          Day {meta.day} · {bookLabel(meta.book)} Ch {meta.chapter}
        </div>
        <div style={{ fontFamily: font.head, fontSize: 22, lineHeight: 1.15, fontWeight: 800, letterSpacing: -0.4 }}>
          {meta.title}
        </div>
        <div style={{ fontSize: 12, color: warm.muted, marginTop: 4, fontStyle: 'italic' }}>{meta.authors}</div>
        <div style={{ fontSize: 10.5, color: warm.muted, marginTop: 3 }}>{lessonAttribution(meta.book)}</div>
      </div>

      <div style={{ flex: 1, overflowY: 'auto', padding: '6px 18px 20px' }}>
        <DisclaimerBanner compact />

        {state.status === 'loading' && (
          <div style={{ color: warm.muted, fontSize: 13, padding: '20px 0', textAlign: 'center' }}>Loading lesson…</div>
        )}

        {state.status === 'error' && (
          <div style={{ textAlign: 'center', padding: '20px 0' }}>
            <div style={{ color: warm.muted, fontSize: 13, marginBottom: 12 }}>
              Couldn&apos;t load this lesson's content. Check your connection and try again.
            </div>
            <button
              type="button"
              onClick={() => setRetryToken((t) => t + 1)}
              style={{
                border: `1.5px solid ${warm.terra}`,
                background: 'none',
                color: warm.terra,
                fontWeight: 700,
                fontSize: 13,
                borderRadius: 10,
                padding: '9px 18px',
                cursor: 'pointer',
              }}
            >
              Try again
            </button>
          </div>
        )}

        {state.status === 'ready' && (
          <>
            <LessonBody blocks={state.content.blocks} scale={fontScale} />
            {hasSourceDoc(meta.book) && (
              <>
                <a
                  href={LESSON_SOURCE_FOLDER_URL}
                  target="_blank"
                  rel="noreferrer noopener"
                  style={{
                    display: 'block',
                    textAlign: 'center',
                    marginTop: 16,
                    padding: '11px 14px',
                    borderRadius: 10,
                    background: warm.terra,
                    color: '#fff',
                    fontWeight: 700,
                    fontSize: 13,
                    textDecoration: 'none',
                  }}
                >
                  Open original lesson document →
                </a>
                <div style={{ fontSize: 10.5, color: warm.muted, marginTop: 8, lineHeight: 1.4, textAlign: 'center' }}>
                  Opens the shared OneDrive folder — look for &quot;{lessonSourceHint(meta)}&quot;.
                </div>
              </>
            )}
          </>
        )}
      </div>
    </div>
  );
}

function LessonBody({ blocks, scale }: { blocks: Block[]; scale: number }) {
  return (
    <div>
      {blocks.map((b, i) => {
        switch (b.type) {
          case 'callout': {
            const stripped = stripWhyIntro(b.text);
            const nlIndex = stripped.indexOf('\n');
            const title = nlIndex >= 0 ? stripped.slice(0, nlIndex) : null;
            const body = nlIndex >= 0 ? stripped.slice(nlIndex + 1) : stripped;
            return <CalloutBox key={i} title={title} body={body} scale={scale} />;
          }
          case 'h1':
            return (
              <div
                key={i}
                style={{
                  fontFamily: font.head,
                  fontSize: 16 * scale,
                  fontWeight: 800,
                  color: warm.terra,
                  marginTop: i === 0 ? 0 : 20,
                  marginBottom: 8,
                }}
              >
                {b.text}
              </div>
            );
          case 'h2':
            return (
              <div
                key={i}
                style={{
                  fontSize: 13 * scale,
                  fontWeight: 700,
                  color: warm.ink,
                  marginTop: 12,
                  marginBottom: 6,
                }}
              >
                {b.text}
              </div>
            );
          case 'li': {
            // Self-check questions are authored as a "Q:" bullet followed by a
            // "ตอบ:" paragraph — style the question as a distinct card so the
            // Q/A pair reads as a unit instead of blending into the list above it.
            const qMatch = /^Q\s*[:：]\s*/.exec(b.text);
            if (qMatch) {
              return (
                <div
                  key={i}
                  style={{
                    display: 'flex',
                    gap: 8,
                    background: chipTone.terra.bg,
                    borderRadius: 10,
                    padding: '8px 10px',
                    marginTop: 16,
                    marginBottom: 2,
                  }}
                >
                  <span style={{ fontWeight: 800, color: chipTone.terra.fg, fontSize: 11.5 * scale }}>Q</span>
                  <span style={{ flex: 1, fontSize: 12.5 * scale, fontWeight: 700, color: chipTone.terra.fg, lineHeight: 1.5 }}>
                    {b.text.slice(qMatch[0].length)}
                  </span>
                </div>
              );
            }
            // Plain bullet lists (references, evidence citations) get a light
            // zebra tint per item so a long run of lines doesn't read as one block.
            // A minority of bullets are themselves dense multi-clause text —
            // split those into a sub-list instead of one dense line.
            const parsed = splitNumberedList(b.text);
            const prose = parsed ? null : splitDenseProse(b.text);
            const chain = parsed || prose ? null : splitArrowChain(b.text);
            return (
              <div
                key={i}
                style={{
                  display: 'flex',
                  gap: 8,
                  background: i % 2 === 1 ? warm.paperDeep : 'transparent',
                  borderRadius: 8,
                  padding: '5px 8px',
                  marginBottom: 3,
                }}
              >
                <span aria-hidden style={{ color: warm.terra, fontSize: 12 * scale, lineHeight: 1.6 }}>
                  ·
                </span>
                <div style={{ flex: 1, fontSize: 12.5 * scale, color: warm.ink2, lineHeight: 1.55 }}>
                  {parsed ? (
                    <>
                      {parsed.intro && <div style={{ whiteSpace: 'pre-wrap', marginBottom: 4 }}>{parsed.intro}</div>}
                      <NumberedItems items={parsed.items} accent={warm.terra} textColor={warm.ink2} />
                    </>
                  ) : prose ? (
                    <PlainBulletItems items={prose} accent={warm.terra} textColor={warm.ink2} />
                  ) : chain ? (
                    <ArrowChainSteps steps={chain} accent={warm.terra} textColor={warm.ink2} />
                  ) : (
                    <span style={{ whiteSpace: 'pre-wrap' }}>{b.text}</span>
                  )}
                </div>
              </div>
            );
          }
          case 'image':
            return (
              <div key={i} style={{ marginBottom: 12 }}>
                <img
                  src={lessonImagePath(b.src)}
                  alt="Figure from the original textbook"
                  loading="lazy"
                  style={{
                    width: '100%',
                    borderRadius: 10,
                    border: `1px solid ${warm.line}`,
                    display: 'block',
                  }}
                />
              </div>
            );
          case 'table': {
            // A few tables were extracted with a caption meant to span the whole
            // table, but the same caption text ended up copied into every column
            // of the first row instead of one wide cell — showing the same
            // paragraph two/three/four times side by side. Pull it out and show
            // it once, above the table, instead.
            const dup = extractDuplicateCaption(b.rows);
            const dataRows = dup ? dup.dataRows : b.rows;

            const ncols = Math.max(...dataRows.map((r) => r.length));
            if (ncols === 1) {
              const shape = classifySingleColumnTable(dataRows.map((r) => r[0] ?? ''));
              // A run of self-contained "title\nbody" rows (e.g. "5 Bedside
              // Pearls") — render each as its own callout card instead of a
              // one-column table where only the first row looked styled.
              if (shape?.kind === 'pearlCards') {
                return (
                  <div key={i}>
                    {shape.cards.map((c, ci) => (
                      <CalloutBox key={ci} title={c.title} body={c.body} scale={scale} />
                    ))}
                  </div>
                );
              }
              // A single title + body pair authored as a 2-row table — same
              // shape as a callout block, so render it identically.
              if (shape?.kind === 'titleBody') {
                return <CalloutBox key={i} title={shape.title} body={shape.body} scale={scale} />;
              }
            }

            return (
              <div key={i} style={{ marginBottom: 12 }}>
                {dup && <CalloutBox title={null} body={dup.caption} scale={scale} />}
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11.5 * scale }}>
                    <tbody>
                      {dataRows.map((row, ri) => (
                        <tr key={ri} style={{ borderBottom: `1px solid ${warm.line}` }}>
                          {row.map((cell, ci) => (
                            <td
                              key={ci}
                              style={{
                                padding: '6px 8px',
                                verticalAlign: 'top',
                                fontWeight: ri === 0 ? 700 : 400,
                                color: ri === 0 ? warm.ink : warm.ink2,
                                background: ri === 0 ? warm.paperDeep : 'transparent',
                                whiteSpace: 'pre-wrap',
                              }}
                            >
                              {cell}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            );
          }
          case 'p': {
            // Self-check answers ("ตอบ: ...") are the most common place a "(1)
            // ... (2) ... (3) ..." list shows up buried in one paragraph — split
            // it the same way callouts are split, using colors that match
            // whichever box style this paragraph is in.
            const aMatch = /^ตอบ\s*[:：]\s*/.exec(b.text);
            const body = aMatch ? b.text.slice(aMatch[0].length) : b.text;
            const accent = aMatch ? chipTone.sage.fg : warm.terra;
            const textColor = aMatch ? chipTone.sage.fg : warm.ink2;
            const parsed = splitNumberedList(body);
            const prose = parsed ? null : splitDenseProse(body);
            const chain = parsed || prose ? null : splitArrowChain(body);
            const content = parsed ? (
              <>
                {parsed.intro && <div style={{ whiteSpace: 'pre-wrap', marginBottom: 6 }}>{parsed.intro}</div>}
                <NumberedItems items={parsed.items} accent={accent} textColor={textColor} />
              </>
            ) : prose ? (
              <PlainBulletItems items={prose} accent={accent} textColor={textColor} />
            ) : chain ? (
              <ArrowChainSteps steps={chain} accent={accent} textColor={textColor} />
            ) : (
              <span style={{ whiteSpace: 'pre-wrap' }}>{body}</span>
            );

            if (aMatch) {
              return (
                <div
                  key={i}
                  style={{
                    background: '#EEEADC', // barely-there sage tint — near-invisible against warm.paper
                    borderRadius: 10,
                    padding: '8px 10px',
                    marginBottom: 12,
                    fontSize: 12.5 * scale,
                    color: chipTone.sage.fg,
                    lineHeight: 1.6,
                  }}
                >
                  <span style={{ fontWeight: 800 }}>ตอบ </span>
                  {content}
                </div>
              );
            }
            return (
              <div key={i} style={{ fontSize: 12.5 * scale, color: warm.ink2, lineHeight: 1.6, marginBottom: 8 }}>
                {content}
              </div>
            );
          }
        }
      })}
    </div>
  );
}
