// Full lesson reader. Content is fetched on demand from public/lessons/day-*.json
// (generated by scripts/extract_lessons.py) rather than bundled, keeping the
// initial app JS small even with 200+ lessons' worth of text.

import { useEffect, useState } from 'react';
import { warm, font, chipTone } from '../../theme/tokens';
import { DisclaimerBanner } from '../../components/Disclaimer';
import { lessonForDay, lessonPath, LESSON_SOURCE_FOLDER_URL, bookLabel, lessonSourceHint } from '../../data/lessons';
import { useProgress } from '../../lib/useProgress';
import { setLessonDone } from '../../lib/progress';
import { useBookmarks } from '../../lib/useBookmarks';
import { toggleBookmark, recordActivity } from '../../lib/storage';
import { lessonBookmarkId } from '../../lib/bookmarkIds';

type Block =
  | { type: 'h1' | 'h2' | 'li' | 'p' | 'callout'; text: string }
  | { type: 'table'; rows: string[][] };

interface LessonContent {
  day: number;
  book: string;
  chapter: number;
  title: string;
  authors: string;
  blocks: Block[];
}

type LoadState =
  | { status: 'loading' }
  | { status: 'error' }
  | { status: 'ready'; content: LessonContent };

// Every lesson's opening callout is authored with a rhetorical lead-in line
// ("ทำไม neonatologist ต้องเข้าใจ <topic>?") before the actual key-points
// summary — redundant once it's inside the app, so it's stripped for display
// only (the source .docx on OneDrive is left untouched).
const WHY_INTRO_RE = /^ทำไม\s*neonatologist\s*ต้องเข้าใจ[^\n]*\?\s*\n+/;

function stripWhyIntro(text: string): string {
  return text.replace(WHY_INTRO_RE, '');
}

// Lots of blocks (callouts, self-check answers, the occasional dense bullet) are
// authored as one sentence enumerating "(1) ... (2) ... (3) ..." separated by
// semicolons or commas — readable in a Word doc, but a wall of text on a phone
// screen. When that pattern is present, split it into a lead-in plus one line
// per numbered point instead of rendering it as a single flowing paragraph.
function splitNumberedList(body: string): { intro: string; items: string[] } | null {
  if (body.includes('\n') || !/\(1\)/.test(body) || !/\(2\)/.test(body)) return null;
  const firstMarker = body.indexOf('(1)');
  if (firstMarker < 0) return null;
  const intro = body.slice(0, firstMarker).trim();
  const items = body
    .slice(firstMarker)
    .split(/[;,]\s*(?=\(\d+\)\s)/)
    .map((s) => s.replace(/^\(\d+\)\s*/, '').trim())
    .filter(Boolean);
  return items.length >= 2 ? { intro, items } : null;
}

function NumberedItems({ items, accent, textColor }: { items: string[]; accent: string; textColor: string }) {
  return (
    <>
      {items.map((item, idx) => (
        <div key={idx} style={{ display: 'flex', gap: 6, marginBottom: idx === items.length - 1 ? 0 : 5 }}>
          <span aria-hidden style={{ color: accent, fontWeight: 700, lineHeight: 1.5, flexShrink: 0 }}>
            {idx + 1}.
          </span>
          <span style={{ flex: 1, whiteSpace: 'pre-wrap', color: textColor }}>{item}</span>
        </div>
      ))}
    </>
  );
}

// Shared box for anything shaped like "title line + body paragraph": real
// `callout` blocks, but also `table` blocks that were authored the same way
// (a 2-row single-column table, or a run of "Pearl" cards) — see the `table`
// case below.
function CalloutBox({ title, body }: { title: string | null; body: string }) {
  const parsed = splitNumberedList(body);
  return (
    <div
      style={{
        background: '#FBEFE3',
        border: `1px solid ${warm.ochre}55`,
        borderRadius: 10,
        padding: '10px 12px',
        marginBottom: 12,
        fontSize: 12.5,
        color: warm.ink2,
        lineHeight: 1.55,
      }}
    >
      {title && <div style={{ whiteSpace: 'pre-wrap', marginBottom: 4 }}>{title}</div>}
      {parsed ? (
        <>
          {parsed.intro && <div style={{ whiteSpace: 'pre-wrap', marginBottom: 6 }}>{parsed.intro}</div>}
          <NumberedItems items={parsed.items} accent={warm.ochre} textColor={warm.ink2} />
        </>
      ) : (
        <div style={{ whiteSpace: 'pre-wrap' }}>{body}</div>
      )}
    </div>
  );
}

export function LessonDetail({ day, onBack }: { day: number; onBack?: () => void }) {
  const [state, setState] = useState<LoadState>({ status: 'loading' });
  const [retryToken, setRetryToken] = useState(0);
  const progress = useProgress();
  const done = Boolean(progress[String(day)]);
  const meta = lessonForDay(day);
  const bookmarks = useBookmarks();
  const bookmarkId = lessonBookmarkId(day);
  const bookmarked = Boolean(bookmarks[bookmarkId]);

  useEffect(() => {
    let cancelled = false;
    setState({ status: 'loading' });
    fetch(lessonPath(day))
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<LessonContent>;
      })
      .then((content) => {
        if (!cancelled) {
          setState({ status: 'ready', content });
          recordActivity(); // reading a lesson keeps the streak alive, even if not marked done
        }
      })
      .catch(() => {
        if (!cancelled) setState({ status: 'error' });
      });
    return () => {
      cancelled = true;
    };
  }, [day, retryToken]);

  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        background: warm.paper,
        color: warm.ink,
        fontFamily: font.ui,
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px 18px 8px',
        }}
      >
        <button
          type="button"
          onClick={onBack}
          style={{ border: 'none', background: 'none', color: warm.terra, fontSize: 14, fontWeight: 600, cursor: 'pointer', padding: 0 }}
        >
          ‹ Lessons
        </button>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <button
            type="button"
            onClick={() => toggleBookmark(bookmarkId)}
            aria-pressed={bookmarked}
            aria-label={bookmarked ? 'Remove bookmark' : 'Bookmark this lesson'}
            style={{
              border: `1px solid ${bookmarked ? warm.ochre : warm.line}`,
              background: bookmarked ? '#FBEFE3' : 'transparent',
              color: bookmarked ? warm.ochre : warm.muted,
              fontSize: 14,
              width: 28,
              height: 28,
              borderRadius: '50%',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              padding: 0,
            }}
          >
            {bookmarked ? '★' : '☆'}
          </button>
          <button
            type="button"
            onClick={() => setLessonDone(day, !done)}
            style={{
              border: `1px solid ${done ? warm.sage : warm.line}`,
              background: done ? warm.sage : 'transparent',
              color: done ? '#fff' : warm.muted,
              fontSize: 11,
              fontWeight: 700,
              padding: '4px 10px',
              borderRadius: 999,
              cursor: 'pointer',
            }}
          >
            {done ? '✓ Done' : 'Mark done'}
          </button>
        </div>
      </div>

      <div style={{ padding: '2px 22px 6px' }}>
        <div style={{ fontSize: 11, fontFamily: font.mono, color: warm.muted, marginBottom: 4 }}>
          Day {meta.day} · {bookLabel(meta.book)} Ch {meta.chapter}
        </div>
        <div style={{ fontFamily: font.head, fontSize: 22, lineHeight: 1.15, fontWeight: 800, letterSpacing: -0.4 }}>
          {meta.title}
        </div>
        <div style={{ fontSize: 12, color: warm.muted, marginTop: 4, fontStyle: 'italic' }}>{meta.authors}</div>
      </div>

      <div style={{ flex: 1, overflowY: 'auto', padding: '6px 18px 20px' }}>
        <DisclaimerBanner compact />

        {state.status === 'loading' && (
          <div style={{ color: warm.muted, fontSize: 13, padding: '20px 0', textAlign: 'center' }}>Loading lesson…</div>
        )}

        {state.status === 'error' && (
          <div style={{ textAlign: 'center', padding: '20px 0' }}>
            <div style={{ color: warm.muted, fontSize: 13, marginBottom: 12 }}>
              Couldn&apos;t load this lesson's content. Check your connection and try again.
            </div>
            <button
              type="button"
              onClick={() => setRetryToken((t) => t + 1)}
              style={{
                border: `1.5px solid ${warm.terra}`,
                background: 'none',
                color: warm.terra,
                fontWeight: 700,
                fontSize: 13,
                borderRadius: 10,
                padding: '9px 18px',
                cursor: 'pointer',
              }}
            >
              Try again
            </button>
          </div>
        )}

        {state.status === 'ready' && (
          <>
            <LessonBody blocks={state.content.blocks} />
            <a
              href={LESSON_SOURCE_FOLDER_URL}
              target="_blank"
              rel="noreferrer noopener"
              style={{
                display: 'block',
                textAlign: 'center',
                marginTop: 16,
                padding: '11px 14px',
                borderRadius: 10,
                background: warm.terra,
                color: '#fff',
                fontWeight: 700,
                fontSize: 13,
                textDecoration: 'none',
              }}
            >
              Open original lesson document →
            </a>
            <div style={{ fontSize: 10.5, color: warm.muted, marginTop: 8, lineHeight: 1.4, textAlign: 'center' }}>
              Opens the shared OneDrive folder — look for &quot;{lessonSourceHint(meta)}&quot;.
            </div>
          </>
        )}
      </div>
    </div>
  );
}

function LessonBody({ blocks }: { blocks: Block[] }) {
  return (
    <div>
      {blocks.map((b, i) => {
        switch (b.type) {
          case 'callout': {
            const stripped = stripWhyIntro(b.text);
            const nlIndex = stripped.indexOf('\n');
            const title = nlIndex >= 0 ? stripped.slice(0, nlIndex) : null;
            const body = nlIndex >= 0 ? stripped.slice(nlIndex + 1) : stripped;
            return <CalloutBox key={i} title={title} body={body} />;
          }
          case 'h1':
            return (
              <div
                key={i}
                style={{
                  fontFamily: font.head,
                  fontSize: 16,
                  fontWeight: 800,
                  color: warm.terra,
                  marginTop: i === 0 ? 0 : 20,
                  marginBottom: 8,
                }}
              >
                {b.text}
              </div>
            );
          case 'h2':
            return (
              <div
                key={i}
                style={{
                  fontSize: 13,
                  fontWeight: 700,
                  color: warm.ink,
                  marginTop: 12,
                  marginBottom: 6,
                }}
              >
                {b.text}
              </div>
            );
          case 'li': {
            // Self-check questions are authored as a "Q:" bullet followed by a
            // "ตอบ:" paragraph — style the question as a distinct card so the
            // Q/A pair reads as a unit instead of blending into the list above it.
            const qMatch = /^Q\s*[:：]\s*/.exec(b.text);
            if (qMatch) {
              return (
                <div
                  key={i}
                  style={{
                    display: 'flex',
                    gap: 8,
                    background: chipTone.terra.bg,
                    borderRadius: 10,
                    padding: '8px 10px',
                    marginTop: 16,
                    marginBottom: 2,
                  }}
                >
                  <span style={{ fontWeight: 800, color: chipTone.terra.fg, fontSize: 11.5 }}>Q</span>
                  <span style={{ flex: 1, fontSize: 12.5, fontWeight: 700, color: chipTone.terra.fg, lineHeight: 1.5 }}>
                    {b.text.slice(qMatch[0].length)}
                  </span>
                </div>
              );
            }
            // Plain bullet lists (references, evidence citations) get a light
            // zebra tint per item so a long run of lines doesn't read as one block.
            // A minority of bullets are themselves "(1) ... (2) ... (3) ..." lists —
            // split those into a sub-list instead of one dense line.
            const parsed = splitNumberedList(b.text);
            return (
              <div
                key={i}
                style={{
                  display: 'flex',
                  gap: 8,
                  background: i % 2 === 1 ? warm.paperDeep : 'transparent',
                  borderRadius: 8,
                  padding: '5px 8px',
                  marginBottom: 3,
                }}
              >
                <span aria-hidden style={{ color: warm.terra, fontSize: 12, lineHeight: 1.6 }}>
                  ·
                </span>
                <div style={{ flex: 1, fontSize: 12.5, color: warm.ink2, lineHeight: 1.55 }}>
                  {parsed ? (
                    <>
                      {parsed.intro && <div style={{ whiteSpace: 'pre-wrap', marginBottom: 4 }}>{parsed.intro}</div>}
                      <NumberedItems items={parsed.items} accent={warm.terra} textColor={warm.ink2} />
                    </>
                  ) : (
                    <span style={{ whiteSpace: 'pre-wrap' }}>{b.text}</span>
                  )}
                </div>
              </div>
            );
          }
          case 'table': {
            const rows = b.rows;

            // A few tables were extracted with a caption meant to span the whole
            // table, but the same caption text ended up copied into every column
            // of the first row instead of one wide cell — showing the same
            // paragraph two/three/four times side by side. Pull it out and show
            // it once, above the table, instead.
            const firstRow = rows[0];
            const hasDuplicateCaption =
              firstRow.length > 1 && new Set(firstRow).size === 1 && firstRow[0].length > 40;
            const caption = hasDuplicateCaption ? firstRow[0] : null;
            const dataRows = hasDuplicateCaption ? rows.slice(1) : rows;

            const ncols = Math.max(...dataRows.map((r) => r.length));
            if (ncols === 1) {
              const cells = dataRows.map((r) => r[0] ?? '');
              // A run of self-contained "title\nbody" rows (e.g. "5 Bedside
              // Pearls") — render each as its own callout card instead of a
              // one-column table where only the first row looked styled.
              if (cells.length >= 3 && cells.every((c) => c.includes('\n'))) {
                return (
                  <div key={i}>
                    {cells.map((c, ci) => {
                      const nl = c.indexOf('\n');
                      return <CalloutBox key={ci} title={c.slice(0, nl)} body={c.slice(nl + 1)} />;
                    })}
                  </div>
                );
              }
              // A single title + body pair authored as a 2-row table — same
              // shape as a callout block, so render it identically.
              if (cells.length === 2) {
                return <CalloutBox key={i} title={cells[0]} body={cells[1]} />;
              }
            }

            return (
              <div key={i} style={{ marginBottom: 12 }}>
                {caption && <CalloutBox title={null} body={caption} />}
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11.5 }}>
                    <tbody>
                      {dataRows.map((row, ri) => (
                        <tr key={ri} style={{ borderBottom: `1px solid ${warm.line}` }}>
                          {row.map((cell, ci) => (
                            <td
                              key={ci}
                              style={{
                                padding: '6px 8px',
                                verticalAlign: 'top',
                                fontWeight: ri === 0 ? 700 : 400,
                                color: ri === 0 ? warm.ink : warm.ink2,
                                background: ri === 0 ? warm.paperDeep : 'transparent',
                                whiteSpace: 'pre-wrap',
                              }}
                            >
                              {cell}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            );
          }
          case 'p': {
            // Self-check answers ("ตอบ: ...") are the most common place a "(1)
            // ... (2) ... (3) ..." list shows up buried in one paragraph — split
            // it the same way callouts are split, using colors that match
            // whichever box style this paragraph is in.
            const aMatch = /^ตอบ\s*[:：]\s*/.exec(b.text);
            const body = aMatch ? b.text.slice(aMatch[0].length) : b.text;
            const accent = aMatch ? chipTone.sage.fg : warm.terra;
            const textColor = aMatch ? chipTone.sage.fg : warm.ink2;
            const parsed = splitNumberedList(body);
            const content = parsed ? (
              <>
                {parsed.intro && <div style={{ whiteSpace: 'pre-wrap', marginBottom: 6 }}>{parsed.intro}</div>}
                <NumberedItems items={parsed.items} accent={accent} textColor={textColor} />
              </>
            ) : (
              <span style={{ whiteSpace: 'pre-wrap' }}>{body}</span>
            );

            if (aMatch) {
              return (
                <div
                  key={i}
                  style={{
                    background: '#EEEADC', // barely-there sage tint — near-invisible against warm.paper
                    borderRadius: 10,
                    padding: '8px 10px',
                    marginBottom: 12,
                    fontSize: 12.5,
                    color: chipTone.sage.fg,
                    lineHeight: 1.6,
                  }}
                >
                  <span style={{ fontWeight: 800 }}>ตอบ </span>
                  {content}
                </div>
              );
            }
            return (
              <div key={i} style={{ fontSize: 12.5, color: warm.ink2, lineHeight: 1.6, marginBottom: 8 }}>
                {content}
              </div>
            );
          }
        }
      })}
    </div>
  );
}
